### ISSUE TITLE
Request to <endpoint>/graphql fail

### ISSUE THREAD

**Issue by alextaymx** [imranhsayed/woo-next#102]
Error: Unexpected token < in JSON at position 0

May I know what caused this issue? I installed the plugins listed on the README, but somehow the endpoint still couldnt work

**Comment by alextaymx** [comment]
ApolloError: Unexpected token < in JSON at position 0
    at new ApolloError (/Users/alex/GitHub/woo-next/node_modules/@apollo/client/errors/errors.cjs.js:31:28)
    at /Users/alex/GitHub/woo-next/node_modules/@apollo/client/core/core.cjs.js:1492:19
    at both (/Users/alex/GitHub/woo-
    



response: Response {
      size: 0,
      timeout: 0,
      [Symbol(Body internals)]: [Object],
      [Symbol(Response internals)]: [Object]
    },
    statusCode: 404,
    bodyText: '<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">\n' +
      '<html><head>\n' +
      '<title>404 Not Found</title>\n' +
      '</head><body>\n' +
      '<h1>Not Found</h1>\n' +
      '<p>The requested URL was not found on this server.</p>\n' +
      '</body></html>\n'
  },
  extraInfo: undefined,
  page: '/'
}

**Comment by imranhsayed** [comment]
Did you try using these?
https://github.com/imranhsayed/woo-next/tree/master/wordpress/plugins

**Comment by JeomJeom** [comment]
@alextaymx Did you manage to solve the issue?
@imranhsayed I've same issue when run the project via `npm run dev`. The plugins have been successfully installed in my Wordpress, I reckon it's nothing to do with the plugins. 
![IMG_7963](https://user-images.githubusercontent.com/38584966/150912188-38757b2f-dd55-43ee-b395-a9911c6b110c.JPG)

![Screen Shot 2022-01-25 at 3 45 28 pm](https://user-images.githubusercontent.com/38584966/150912575-3884c816-d94f-428b-85ad-476bfc3a2900.png)

Any idea to fix it?

**Comment by edu-damasceno** [comment]
I had a "maintenance mode" plugin active and I was having the same issue. I deleted it and it worked.
