### ISSUE TITLE
Build error occurred

### ISSUE THREAD

**Issue by jawadan** [imranhsayed/woo-next#112]
I am getting this error, how can I fix that?

Error: request to https://gpanel.goonut.com/graphql/graphql failed, reason: unable to verify the first certificate
--
19:32:08.278 | at new ApolloError (/vercel/path0/node_modules/@apollo/client/errors/errors.cjs.js:31:28)
19:32:08.278 | at /vercel/path0/node_modules/@apollo/client/core/core.cjs.js:1493:19
19:32:08.278 | at both (/vercel/path0/node_modules/@apollo/client/utilities/utilities.cjs.js:963:53)
19:32:08.279 | at /vercel/path0/node_modules/@apollo/client/utilities/utilities.cjs.js:956:72
19:32:08.279 | at new Promise (<anonymous>)
19:32:08.279 | at Object.then (/vercel/path0/node_modules/@apollo/client/utilities/utilities.cjs.js:956:24)
19:32:08.279 | at Object.error (/vercel/path0/node_modules/@apollo/client/utilities/utilities.cjs.js:964:49)
19:32:08.279 | at notifySubscription (/vercel/path0/node_modules/zen-observable/lib/Observable.js:140:18)
19:32:08.279 | at onNotify (/vercel/path0/node_modules/zen-observable/lib/Observable.js:179:3)
19:32:08.279 | at SubscriptionObserver.error (/vercel/path0/node_modules/zen-observable/lib/Observable.js:240:7) {

**Comment by ThianBrodie** [comment]
I have same error, before that in console I have: error - Error: Only absolute URLs are supported

**Comment by asheroto** [comment]
![image](https://user-images.githubusercontent.com/49938263/178745227-fcfb5028-93bb-4d93-ae63-e11479e02514.png)

**Comment by w3bdesign** [comment]
Have you set the .env variables correctly?

Where is the Wordpress installation located?
