### ISSUE TITLE
Error during build in Vercel Deplayment

### ISSUE THREAD

**Issue by thefoxes86** [imranhsayed/woo-next#78]
Hi, 
while Verce try to make a build for the deploy, it exit with this error:

`18:38:56.952
$ next build
18:38:57.834
18:38:57.834
> Build error occurred
18:38:57.836
TypeError [ERR_INVALID_URL]: Invalid URL: undefined
18:38:57.836
    at onParseError (internal/url.js:259:9)
18:38:57.836
    at new URL (internal/url.js:335:5)
18:38:57.836
    at Object.<anonymous> (/vercel/path0/next.config.__vercel_builder_backup__.js:2:37)
18:38:57.836
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
18:38:57.836
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
18:38:57.836
    at Module.load (internal/modules/cjs/loader.js:928:32)
18:38:57.836
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
18:38:57.836
    at Module.require (internal/modules/cjs/loader.js:952:19)
18:38:57.836
    at require (internal/modules/cjs/helpers.js:88:18)
18:38:57.836
    at module.exports (/vercel/path0/next.config.js:3:18) {
18:38:57.836
  input: 'undefined',
18:38:57.836
  code: 'ERR_INVALID_URL'
18:38:57.836
}
18:38:57.856
error Command failed with exit code 1.
18:38:57.856
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
18:38:57.873
Error: Command "yarn run build" exited with 1`

Do you know why and how can I solve this trouble ?

Thanks

**Comment by imranhsayed** [comment]
It appears to be the issue with URL.
Please check your `.env` file and follow the [README](https://github.com/imranhsayed/woo-next/blob/master/README.md)
https://github.com/imranhsayed/woo-next/blob/master/.env-example

**Comment by thefoxes86** [comment]
Thanks, but the problems was different. Inside the gitgnore there was also
the .env file so the push didn't upload that.

Il giorno mer 26 mag 2021 alle ore 16:43 Imran Sayed <
***@***.***> ha scritto:

**Comment by thefoxes86** [comment]
Solved by fixing the gitgnore file that excluded the .env

**Comment by imranhsayed** [comment]
Thank you. 
The .env file should never be committed because it contains your private keys and variables. That's why it's in gitignore. 

The .env variables should be added in ur hosting provider deploy settings.
